version: 2.1
orbs:
  # Updated
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          record: true
          
build:
  docker:
    - image: circleci/node:latest
  steps:
    - checkout
    - npm install
    - npm run test:consumer
    - npm run publish:pact
    - npm run publish:pact
    - npm run test:provider
